// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp89woAYfgizHVUYnwZe3iqVo5PiDDlbc',
    appId: '1:341482426720:web:03a3323117c1e1ca118e05',
    messagingSenderId: '341482426720',
    projectId: 'devtrails-8fce6',
    authDomain: 'devtrails-8fce6.firebaseapp.com',
    storageBucket: 'devtrails-8fce6.firebasestorage.app',
    measurementId: 'G-Q2Q97164E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDfC5KeFM0eIrfGxWsE0CSE5mdwGMmQ8Y',
    appId: '1:341482426720:android:352d5c5040aca6e0118e05',
    messagingSenderId: '341482426720',
    projectId: 'devtrails-8fce6',
    storageBucket: 'devtrails-8fce6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp89woAYfgizHVUYnwZe3iqVo5PiDDlbc',
    appId: '1:341482426720:web:03a3323117c1e1ca118e05',
    messagingSenderId: '341482426720',
    projectId: 'devtrails-8fce6',
    authDomain: 'devtrails-8fce6.firebaseapp.com',
    storageBucket: 'devtrails-8fce6.firebasestorage.app',
    measurementId: 'G-Q2Q97164E7',
  );
}
